name: Lint and test

on:
  push:
    branches:
      - main

jobs:

  test:

    runs-on: ubuntu-latest

    name: Run linting and tests

  steps:

  - uses: actions/checkout@v4

  - uses: bahmutov/npm-install@v1

  - run: npm run lint (Run ESLint)

  - run: npm run test (Run Jest)
